from typing import Any, Dict, List


def signal_registry() -> Dict[str, Any]:
    signals = [
        signal(
            "enemy_seen_by_detector",
            "Enemy seen by trained detector",
            "contact_enemy",
            "trained_detector",
            "A local trained object detector returned an enemy body/head box.",
            "This is not a tactical conclusion or proof of a bad peek.",
            "boolean with confidence 0-1 and bbox_norm",
            ["Claim a visible enemy/body/head box exists in the cited frame."],
            ["Do not infer enemy intent, exact agent, or why the duel was lost from this alone."],
        ),
        signal(
            "enemy_seen_by_vlm",
            "Enemy seen by local VLM",
            "contact_enemy",
            "vlm",
            "The local vision-language model claims enemy/contact is visible and cites frame evidence.",
            "This is not ground truth; it is model perception.",
            "true/false/uncertain with confidence 0-1",
            ["Use as supporting visual evidence when frame references are present."],
            ["Do not override trained detector/user labels without lowering confidence."],
        ),
        signal(
            "contact_proxy",
            "Contact proxy",
            "contact_enemy",
            "heuristic",
            "A pressure cue from motion, red regions, killfeed color, crosshair activity, or HUD changes.",
            "This does not prove an enemy is visible.",
            "0-1 score",
            ["Say possible pressure/contact cue."],
            ["Do not say confirmed enemy detected."],
        ),
        signal(
            "death_event",
            "Death event",
            "death",
            "ocr_hud_user",
            "Evidence that the player died at or near a timestamp from killfeed, combat report, or manual marker.",
            "This does not identify the enemy position or the mistake.",
            "timestamp plus confidence 0-1",
            ["Anchor a review clip around the event."],
            ["Do not infer the cause of death without clip evidence."],
        ),
        signal(
            "combat_report_score",
            "Combat report score",
            "death",
            "heuristic_ocr",
            "Visual/OCR confidence that the right-side combat report panel is present.",
            "A sustained panel is not a new death event by itself.",
            "0-1 score",
            ["Support death detection or aftermath context."],
            ["Do not repeatedly mark deaths while the same panel remains visible."],
        ),
        signal(
            "crosshair_activity",
            "Crosshair activity",
            "aim",
            "heuristic",
            "Pixel variation inside the calibrated crosshair region.",
            "This is not directly aim quality or head placement.",
            "0-1 normalized activity",
            ["Use as one input to crosshair stability/correction risk."],
            ["Do not call it bad aim alone."],
        ),
        signal(
            "crosshair_drift",
            "Crosshair drift",
            "aim",
            "heuristic",
            "Frame-to-frame change inside the crosshair crop.",
            "This does not know whether the movement was intentional.",
            "0-1 normalized motion",
            ["Support claims about late correction only when aligned with contact evidence."],
            ["Do not claim overflick/underflick without enemy/head reference."],
        ),
        signal(
            "crosshair_to_contact",
            "Crosshair to contact distance",
            "aim",
            "trained_or_proxy",
            "Normalized distance between estimated crosshair center and trained detector box or contact proxy center.",
            "Proxy-based distance is not true enemy-head offset.",
            "distance 0-1 plus source",
            ["Use trained-detector source for stronger aim placement claims."],
            ["Do not present proxy-based distance as headshot alignment."],
        ),
        signal(
            "movement_risk",
            "Movement risk",
            "mechanics",
            "heuristic",
            "Screen motion during contact/proxy frames.",
            "This does not distinguish counter-strafing, jiggle peeking, recoil, or camera shake.",
            "stable/high/moving during contact",
            ["Suggest verifying movement timing around contact."],
            ["Do not claim the player was definitely running while shooting."],
        ),
        signal(
            "minimap_motion",
            "Minimap motion",
            "context",
            "heuristic",
            "Frame-to-frame change inside the minimap region.",
            "This is not semantic map understanding by itself.",
            "0-1 normalized motion",
            ["Use as timing/rotation cue when combined with OCR/VLM/HUD context."],
            ["Do not infer exact teammate/enemy positions from this alone."],
        ),
        signal(
            "round_score",
            "Round score",
            "ocr_context",
            "ocr_vlm",
            "Visible top HUD score values for ally/enemy teams.",
            "This is not the round number unless converted as ally + enemy + 1.",
            "ally/enemy integers with confidence",
            ["Infer round number when both scores are reliable."],
            ["Do not apply low-confidence OCR over manual correction."],
        ),
        signal(
            "claim_confidence",
            "Claim confidence",
            "coach",
            "derived",
            "Confidence in a specific coaching claim after considering evidence quality and source strength.",
            "This is not model certainty for the whole match.",
            "0-1 per claim/category",
            ["Rank advice and show uncertainty."],
            ["Do not hide weak evidence behind a high overall summary score."],
        ),
    ]
    return {
        "kind": "signal_registry",
        "version": 1,
        "signals": signals,
        "by_id": {item["id"]: item for item in signals},
        "summary": f"{len(signals)} gameplay signal definitions with source and claim boundaries.",
    }


def signal(
    signal_id: str,
    display_name: str,
    category: str,
    source_type: str,
    meaning: str,
    not_meaning: str,
    scale: str,
    allowed_claims: List[str],
    forbidden_claims: List[str],
) -> Dict[str, Any]:
    return {
        "id": signal_id,
        "display_name": display_name,
        "category": category,
        "source_type": source_type,
        "meaning": meaning,
        "not_meaning": not_meaning,
        "scale": scale,
        "thresholds": {},
        "trained": source_type == "trained_detector",
        "heuristic": "heuristic" in source_type,
        "ocr": "ocr" in source_type,
        "vlm": source_type == "vlm",
        "user_label": "user" in source_type,
        "allowed_claims": allowed_claims,
        "forbidden_claims": forbidden_claims,
        "consumers": ["ui", "clip_coach_prompt", "memory", "reports"],
    }
